### ISSUE TITLE
Update source code

### ISSUE THREAD

**Issue by RuizuKun-Dev** [Dinnyesensei/DataEditor_Source#1]
Hi, I’d like to contribute to the project and require the latest version of the plugin.

do you currently use Rojo? I’d make things a lot easier

**Comment by xsticcydev** [comment]
Hello! Currently github seems to struggle with thge rbxmx file but I updated the source code to the latest version.

**Comment by RuizuKun-Dev** [comment]
Thanks for updating the source code!

You should refactor your code into smaller modules, the current file is too big and not considered good practice.
